// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _VGAME_CONSOLE_TOP_H_
#define _VGAME_CONSOLE_TOP_H_  // guard

#include "verilated.h"

//==========

class VGame_Console_TOP__Syms;
class VGame_Console_TOP_VerilatedVcd;
class VGame_Console_TOP_Pixel_Reader;
class VGame_Console_TOP_Decompresser;


//----------

VL_MODULE(VGame_Console_TOP) {
  public:
    // CELLS
    // Public to allow access to /*verilator_public*/ items;
    // otherwise the application code can consider these internals.
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_bg1;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_bg2;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_ch1;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_ch2;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_ch3;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_ch4;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_sc;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_st;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_un1;
    VGame_Console_TOP_Pixel_Reader* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_un2;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_uni1;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_uni2;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_script;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_status;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_ch1;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_ch2;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_ch3;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_ch4;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_bg1;
    VGame_Console_TOP_Decompresser* __PVT__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_decomp_bg2;
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(clk,0,0);
    VL_IN8(resetn,0,0);
    VL_IN8(joypad_state_in,7,0);
    VL_OUT8(joypad_irq,0,0);
    VL_OUT8(DDR3_CPU_valid,0,0);
    VL_IN8(DDR3_CPU_ready,0,0);
    VL_OUT8(DDR3_CPU_wstrb,3,0);
    VL_OUT8(DDR3_CPU_burst_len,7,0);
    VL_OUT8(DDR3_CPU_burst_en,0,0);
    VL_OUT8(DDR3_PPU_valid,0,0);
    VL_IN8(DDR3_PPU_ready,0,0);
    VL_OUT8(DDR3_PPU_wstrb,3,0);
    VL_OUT8(DDR3_PPU_burst_len,7,0);
    VL_OUT8(DDR3_PPU_burst_en,0,0);
    VL_OUT8(BRAM0_wen,0,0);
    VL_OUT8(BRAM0_wstrb,7,0);
    VL_OUT8(BRAM0_ren,0,0);
    VL_OUT8(BRAM1_wen,0,0);
    VL_OUT8(BRAM1_wstrb,7,0);
    VL_OUT8(BRAM1_ren,0,0);
    VL_OUT8(BRAM2_wen,0,0);
    VL_OUT8(BRAM2_wstrb,7,0);
    VL_OUT8(BRAM2_ren,0,0);
    VL_OUT8(BRAM3_wen,0,0);
    VL_OUT8(BRAM3_wstrb,7,0);
    VL_OUT8(BRAM3_ren,0,0);
    VL_OUT8(BRAM4_en_a,0,0);
    VL_OUT8(BRAM4_wstrb_a,3,0);
    VL_OUT8(BRAM4_en_b,0,0);
    VL_OUT8(BRAM4_wstrb_b,3,0);
    VL_OUT8(BRAM5_en_a,0,0);
    VL_OUT8(BRAM5_wstrb_a,3,0);
    VL_OUT8(BRAM5_en_b,0,0);
    VL_OUT8(BRAM5_wstrb_b,3,0);
    VL_OUT8(BRAM6_en_a,0,0);
    VL_OUT8(BRAM6_wstrb_a,3,0);
    VL_OUT8(BRAM6_en_b,0,0);
    VL_OUT8(BRAM6_wstrb_b,3,0);
    VL_OUT8(BRAM13_en_a,0,0);
    VL_OUT8(BRAM13_wstrb_a,3,0);
    VL_OUT8(BRAM13_en_b,0,0);
    VL_OUT8(BRAM13_wstrb_b,3,0);
    VL_OUT8(BRAM14_en_a,0,0);
    VL_OUT8(BRAM14_wstrb_a,3,0);
    VL_OUT8(BRAM14_en_b,0,0);
    VL_OUT8(BRAM14_wstrb_b,3,0);
    VL_OUT8(BRAM7_en_a,0,0);
    VL_OUT8(BRAM7_we_a,0,0);
    VL_OUT8(BRAM7_en_b,0,0);
    VL_OUT8(BRAM8_en_a,0,0);
    VL_OUT8(BRAM8_we_a,0,0);
    VL_OUT8(BRAM8_en_b,0,0);
    VL_OUT8(BRAM9_en_a,0,0);
    VL_OUT8(BRAM9_we_a,0,0);
    VL_OUT8(BRAM9_en_b,0,0);
    VL_OUT8(BRAM10_en_a,0,0);
    VL_OUT8(BRAM10_we_a,0,0);
    VL_OUT8(BRAM10_en_b,0,0);
    VL_OUT8(BRAM11_en_a,0,0);
    VL_OUT8(BRAM11_we_a,0,0);
    VL_OUT8(BRAM11_en_b,0,0);
    VL_OUT8(BRAM12_en_a,0,0);
    VL_OUT8(BRAM12_we_a,0,0);
    VL_OUT8(BRAM12_en_b,0,0);
    VL_OUT8(LUT_we,0,0);
    VL_OUT8(LUT_addr_w,7,0);
    VL_OUT8(LUT_addr_r1,7,0);
    VL_OUT8(LUT_addr_r2,7,0);
    VL_OUT8(Final_pixel_valid,0,0);
    VL_OUT8(Font_Line_End,0,0);
    VL_OUT8(Font_Frame_End,0,0);
    VL_OUT16(BRAM0_waddr,8,0);
    VL_OUT16(BRAM0_raddr,8,0);
    VL_OUT16(BRAM1_waddr,8,0);
    VL_OUT16(BRAM1_raddr,8,0);
    VL_OUT16(BRAM2_waddr,8,0);
    VL_OUT16(BRAM2_raddr,8,0);
    VL_OUT16(BRAM3_waddr,8,0);
    VL_OUT16(BRAM3_raddr,8,0);
    VL_OUT16(BRAM4_addr_a,9,0);
    VL_OUT16(BRAM4_addr_b,9,0);
    VL_OUT16(BRAM5_addr_a,9,0);
    VL_OUT16(BRAM5_addr_b,9,0);
    VL_OUT16(BRAM6_addr_a,9,0);
    VL_OUT16(BRAM6_addr_b,9,0);
    VL_OUT16(BRAM13_addr_a,9,0);
    VL_OUT16(BRAM13_addr_b,9,0);
    VL_OUT16(BRAM14_addr_a,9,0);
    VL_OUT16(BRAM14_addr_b,9,0);
    VL_OUT16(BRAM7_addr_a,8,0);
    VL_OUT16(BRAM7_addr_b,8,0);
    VL_OUT16(BRAM8_addr_a,8,0);
    VL_OUT16(BRAM8_addr_b,8,0);
    VL_OUT16(BRAM9_addr_a,8,0);
    VL_OUT16(BRAM9_addr_b,8,0);
    VL_OUT16(BRAM10_addr_a,8,0);
    VL_OUT16(BRAM10_addr_b,8,0);
    VL_OUT16(BRAM11_addr_a,8,0);
    VL_OUT16(BRAM11_addr_b,8,0);
    VL_OUT16(BRAM12_addr_a,8,0);
    VL_OUT16(BRAM12_addr_b,8,0);
    VL_OUT(DDR3_CPU_addr,31,0);
    VL_OUT(DDR3_CPU_wdata,31,0);
    VL_IN(DDR3_CPU_rdata,31,0);
    VL_OUT(DDR3_PPU_addr,31,0);
    VL_OUT(DDR3_PPU_wdata,31,0);
    VL_IN(DDR3_PPU_rdata,31,0);
    VL_OUTW(BRAM0_din,71,0,3);
    VL_INW(BRAM0_dout,71,0,3);
    VL_OUTW(BRAM1_din,71,0,3);
    VL_INW(BRAM1_dout,71,0,3);
    VL_OUTW(BRAM2_din,71,0,3);
    VL_INW(BRAM2_dout,71,0,3);
    VL_OUTW(BRAM3_din,71,0,3);
    VL_INW(BRAM3_dout,71,0,3);
    VL_OUT(BRAM4_din_a,31,0);
    VL_IN(BRAM4_dout_a,31,0);
    VL_OUT(BRAM4_din_b,31,0);
    VL_IN(BRAM4_dout_b,31,0);
    VL_OUT(BRAM5_din_a,31,0);
    VL_IN(BRAM5_dout_a,31,0);
    VL_OUT(BRAM5_din_b,31,0);
    VL_IN(BRAM5_dout_b,31,0);
    VL_OUT(BRAM6_din_a,31,0);
    VL_IN(BRAM6_dout_a,31,0);
    VL_OUT(BRAM6_din_b,31,0);
    VL_IN(BRAM6_dout_b,31,0);
    VL_OUT(BRAM13_din_a,31,0);
    VL_IN(BRAM13_dout_a,31,0);
    VL_OUT(BRAM13_din_b,31,0);
    VL_IN(BRAM13_dout_b,31,0);
    VL_OUT(BRAM14_din_a,31,0);
    VL_IN(BRAM14_dout_a,31,0);
    VL_OUT(BRAM14_din_b,31,0);
    VL_IN(BRAM14_dout_b,31,0);
    VL_OUT(LUT_data_in,17,0);
    VL_IN(LUT_data_out1,17,0);
    VL_IN(LUT_data_out2,17,0);
    VL_OUT(Final_pixel_RGB,17,0);
    VL_OUT64(BRAM7_din_a,63,0);
    VL_IN64(BRAM7_dout_b,63,0);
    VL_OUT64(BRAM8_din_a,63,0);
    VL_IN64(BRAM8_dout_b,63,0);
    VL_OUT64(BRAM9_din_a,63,0);
    VL_IN64(BRAM9_dout_b,63,0);
    VL_OUT64(BRAM10_din_a,63,0);
    VL_IN64(BRAM10_dout_b,63,0);
    VL_OUT64(BRAM11_din_a,63,0);
    VL_IN64(BRAM11_dout_b,63,0);
    VL_OUT64(BRAM12_din_a,63,0);
    VL_IN64(BRAM12_dout_b,63,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ Game_Console_TOP__DOT__cpu_mem_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__cpu_mem_instr;
        CData/*3:0*/ Game_Console_TOP__DOT__cpu_mem_wstrb;
        CData/*0:0*/ Game_Console_TOP__DOT__cpu_la_read;
        CData/*0:0*/ Game_Console_TOP__DOT__cpu_la_write;
        CData/*3:0*/ Game_Console_TOP__DOT__cpu_la_wstrb;
        CData/*0:0*/ Game_Console_TOP__DOT__cpu_trap;
        CData/*0:0*/ Game_Console_TOP__DOT__cache_cpu_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__cache_emem_valid;
        CData/*3:0*/ Game_Console_TOP__DOT__cache_emem_wstrb;
        CData/*7:0*/ Game_Console_TOP__DOT__cache_emem_burst_len;
        CData/*0:0*/ Game_Console_TOP__DOT__cache_emem_burst_en;
        CData/*0:0*/ Game_Console_TOP__DOT__cache_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__PPU_start;
        CData/*0:0*/ Game_Console_TOP__DOT__dec_emem_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__ppu_emem_valid;
        CData/*3:0*/ Game_Console_TOP__DOT__ppu_emem_wstrb;
        CData/*7:0*/ Game_Console_TOP__DOT__ppu_emem_burst_len;
        CData/*0:0*/ Game_Console_TOP__DOT__ppu_emem_burst_en;
        CData/*7:0*/ Game_Console_TOP__DOT__ppu_lut_addr_r1;
        CData/*7:0*/ Game_Console_TOP__DOT__ppu_lut_addr_r2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__trace_valid;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__reg_sh;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__irq_delay;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__irq_active;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_mul_wr;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_mul_wait;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_mul_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_div_wr;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_div_wait;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_div_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_int_wr;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_int_ready;
        CData/*1:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_wordsize;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_do_prefetch;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_do_rinst;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_do_rdata;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_do_wdata;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_xfer;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_la_secondword;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_la_firstword_reg;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__last_mem_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__prefetched_high_word;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__clear_prefetched_high_word;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_done;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_lui;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_auipc;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_jal;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_jalr;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_beq;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_bne;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_blt;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_bge;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_bltu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_bgeu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_lb;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_lh;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_lw;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_lbu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_lhu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_sb;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_sh;
    };
    struct {
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_sw;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_addi;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_slti;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_sltiu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_xori;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_ori;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_andi;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_slli;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_srli;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_srai;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_add;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_sub;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_sll;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_slt;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_sltu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_xor;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_srl;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_sra;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_or;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_and;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_rdcycle;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_rdcycleh;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_rdinstr;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_rdinstrh;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_ecall_ebreak;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_fence;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_getq;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_setq;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_retirq;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_maskirq;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_waitirq;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_timer;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__instr_trap;
        CData/*5:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoded_rd;
        CData/*5:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoded_rs1;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoded_rs2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoder_trigger;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoder_trigger_q;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoder_pseudo_trigger;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoder_pseudo_trigger_q;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__compressed_instr;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_lui_auipc_jal;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_lb_lh_lw_lbu_lhu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_slli_srli_srai;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_sb_sh_sw;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_sll_srl_sra;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_lui_auipc_jal_jalr_addi_add_sub;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_slti_blt_slt;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_sltiu_bltu_sltu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_beq_bne_blt_bge_bltu_bgeu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_lbu_lhu_lw;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_alu_reg_imm;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_alu_reg_reg;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_compare;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_insn_rs1;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_insn_rs2;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_insn_rd;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_rs1val_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_rs2val_valid;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__q_insn_rs1;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__q_insn_rs2;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__q_insn_rd;
    };
    struct {
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_next;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__launch_next_insn;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_valid_insn;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cached_insn_rs1;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cached_insn_rs2;
        CData/*4:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cached_insn_rd;
        CData/*7:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cpu_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_cpu__DOT__irq_state;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__set_mem_do_rinst;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__set_mem_do_rdata;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__set_mem_do_wdata;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_store;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_stalu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_branch;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_compr;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_trace;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_is_lu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_is_lh;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_is_lb;
        CData/*5:0*/ Game_Console_TOP__DOT__u_cpu__DOT__latched_rd;
        CData/*3:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_timeout_counter;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_timeout;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__do_waitirq;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_out_0;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_out_0_q;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_wait;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_wait_2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_eq;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_ltu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_lts;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__clear_prefetched_high_word_q;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cpuregs_write;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mul;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulh;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhsu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__instr_mulhu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__instr_any_mulh;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__pcpi_wait_q;
        CData/*6:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__mul_counter;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__mul_waiting;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__mul_finish;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__instr_div;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__instr_divu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__instr_rem;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__instr_remu;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__pcpi_wait_q;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__start;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__running;
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__outsign;
        CData/*3:0*/ Game_Console_TOP__DOT__u_icache__DOT__main_state;
        CData/*3:0*/ Game_Console_TOP__DOT__u_icache__DOT__main_next;
        CData/*0:0*/ Game_Console_TOP__DOT__u_icache__DOT__cpu_tag_save;
        CData/*3:0*/ Game_Console_TOP__DOT__u_icache__DOT__burst_counter;
        CData/*0:0*/ Game_Console_TOP__DOT__u_icache__DOT__burst_counter_reset;
        CData/*0:0*/ Game_Console_TOP__DOT__u_icache__DOT__burst_counter_plus;
        CData/*0:0*/ Game_Console_TOP__DOT__u_icache__DOT__word_buffer_wen_0;
        CData/*0:0*/ Game_Console_TOP__DOT__u_icache__DOT__word_buffer_wen_1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_icache__DOT__word_buffer_wen_2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_icache__DOT__word_buffer_wen_3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_icache__DOT__random_bit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sel_ddr3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sel_ppu_reg;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sel_lut;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sel_font_map;
    };
    struct {
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sel_bram4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sel_bram5;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sel_bram6;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sel_bram13;
        CData/*3:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__main_state;
        CData/*3:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__main_state_next;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_bram4_r;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_bram4_w;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_bram5_r;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_bram5_w;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_bram6_r;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_bram6_w;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_bram13_r;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_bram13_w;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_font_map_r;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_font_map_w;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_lut_w;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_ppu_reg_r;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__sampling_ppu_reg_w;
        CData/*0:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__joypad_irq_pending;
        CData/*7:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__joypad_state_latched;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__Clk_Counter;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__proc_final_pixel_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__font_mixed_pixel_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__font_line_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__font_frame_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__All_Decompresser_is_IDLE;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_fifo_count;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_fifo_front;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_fifo_rear;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_fifo_count;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_fifo_front;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_fifo_rear;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_fifo_count;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_fifo_front;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_fifo_rear;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_fifo_count;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_fifo_front;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_fifo_rear;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_fifo_count;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_fifo_front;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_fifo_rear;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_fifo_count;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_fifo_front;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_fifo_rear;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_fifo_count;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_fifo_front;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_fifo_rear;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_fifo_count;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_fifo_front;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_fifo_rear;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_fifo_inc_want;
    };
    struct {
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_fifo_inc_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_fifo_dec_want;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_fifo_r_master;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_fifo_r_master;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__main_state;
        CData/*2:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__BRAM7_read_state;
        CData/*2:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__BRAM7_read_state_next;
        CData/*2:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__BRAM8_read_state;
        CData/*2:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__BRAM8_read_state_next;
        CData/*2:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__BRAM9_read_state;
        CData/*2:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__BRAM9_read_state_next;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__round_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__is_urgent_mode;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__emem_r_counter;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache1_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache1_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache2_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache2_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache3_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache3_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache4_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache4_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req11_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req11_exclusive_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req12_exclusive_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req12_exclusive_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_exclusive_hit;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_hit3;
    };
    struct {
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_hit1;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_hit2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_hit3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_hit4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_is_zero;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_is_zero;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__random_counter_0_3;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__random_counter_0_1;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__random_counter_0_2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req11_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req12_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__is_new_pixel;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z1_is_trans;
    };
    struct {
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z1_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z1_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z1_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z2_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z2_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z2_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z2_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z3_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z3_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z3_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z3_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z4_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z4_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z4_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z4_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z5_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z5_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z5_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z5_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z6_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z6_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z6_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z6_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z7_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z7_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z7_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z7_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z8_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z8_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z8_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z8_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z9_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z9_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z9_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z9_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z10_is_trans;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z10_a;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z10_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z10_ready;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipeline_move;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe1_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe1_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe2_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe2_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe3_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe3_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe4_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe4_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe5_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe5_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe6_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe6_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe7_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe7_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe8_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe8_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe9_is_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe9_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__all_fsm_reset;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z1_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z1_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z2_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z2_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z3_state;
    };
    struct {
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z3_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z4_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z4_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z5_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z5_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z6_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z6_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z7_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z7_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z8_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z8_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z9_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z9_state_next;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z10_state;
        CData/*1:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z10_state_next;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__main_state;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__main_state_next;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__fontmap_skid_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__korea_bitmap_skid_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__ascii_bitmap_skid_data;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__ascii_bitmap_skid_valid;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__custom_tile_bitmap_skid_data;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__custom_tile_bitmap_skid_valid;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pixel_state;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pixel_state_next;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__output_state;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__output_state_next;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__font_state;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__font_state_next;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_0_39;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_0_15;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_0_14;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_font_x;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_0_39_reset;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_font_x_reset;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_font_x_reset_reg;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_font_x_reset_reg_reg;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_1_reg_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_2_reg_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_3_reg_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_4_reg_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_5_reg_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_6_reg_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_7_reg_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_8_reg_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_1_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_2_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_3_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_4_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_5_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_6_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_7_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_8_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_shift;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__output_pixel_inc;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_reg_shift;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_reg_all_full;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__font_mix_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_w_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipeline_move;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_valid_next;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_counter_16_next;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_font_x_next;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_font_y_next;
    };
    struct {
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_next_line_next;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__bram_font_read_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__bram_font_read_ena_reg;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__bram_map_read_ena;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__bram_map_read_ena_reg;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_valid;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_counter_16;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_font_x;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_font_y;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe1_next_line;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe2_valid;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe2_mask;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe2_font_x;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe2_font_y;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe2_counter_16;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe2_next_line;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe3_valid;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe3_font_x;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe3_font_y;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe3_counter_16;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe3_next_line;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_is_korea;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_is_ascii;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_is_custom;
        CData/*4:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_jung_sung_index;
        CData/*4:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_chong_sung_index;
        CData/*4:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_cho_sung_index;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_font_x;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_font_y;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_counter_16;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_next_line;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_valid;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_mask;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_cho_sung_what_bram;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_custom_what_bram;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_is_korea;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_is_ascii;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_is_custom;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_font_x;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_font_y;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_counter_16;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe5_next_line;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_valid;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_is_korea;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_is_ascii;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_is_custom;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_ascii_font_bitmap;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_custom_tile_bitmap;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_font_x;
        CData/*5:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_font_y;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_counter_16;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_next_line;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__cho_sung_set;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__jung_sung_set;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__chong_sung_set;
        CData/*4:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__chong_sung_index;
        CData/*4:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__cho_sung_index;
        CData/*4:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__jung_sung_index;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__is_korea_wire;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__is_ascii_wire;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__is_custom_wire;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__do_not_need_mix;
        CData/*2:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__organized_alpha_0_4;
    };
    struct {
        SData/*15:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_16bit_buffer;
        SData/*14:0*/ Game_Console_TOP__DOT__u_icache__DOT__cpu_I_tag;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_fifo_count;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_fifo_front;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_fifo_rear;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_fifo_count;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_fifo_front;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_fifo_rear;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__next_should_read_layer;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__last_read_basic;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__last_read_urgent;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__valid_req;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__urgent_req;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__basic_req;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__masked_req;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__should_read_layer;
        SData/*11:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__total_req;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe1_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe1_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe1_B;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe2_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe2_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe2_B;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe3_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe3_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe3_B;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe4_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe4_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe4_B;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe5_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe5_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe5_B;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe6_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe6_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe6_B;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe7_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe7_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe7_B;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe8_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe8_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe8_B;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe9_R;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe9_G;
        SData/*14:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Pipe9_B;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__main_state_counter_x;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__main_state_counter_y;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__main_state_counter_x_next;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__main_state_counter_y_next;
        SData/*15:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__fontmap_skid_data;
        SData/*15:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__korea_bitmap_skid_data;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__output_pixel_x;
        SData/*8:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__output_pixel_y;
        SData/*15:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe3_UTF16;
        SData/*15:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe4_UTF16;
        SData/*15:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pipe6_korea_font_bitmap;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__cho_sung_bram_ad;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__jung_sung_bram_ad;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__chong_sung_bram_ad;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__ascii_bram_ad;
        SData/*9:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__custom_tile_bram_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__cpu_mem_addr;
        IData/*31:0*/ Game_Console_TOP__DOT__cpu_mem_wdata;
        IData/*31:0*/ Game_Console_TOP__DOT__cpu_la_wdata;
        IData/*31:0*/ Game_Console_TOP__DOT__cache_cpu_rdata;
    };
    struct {
        IData/*31:0*/ Game_Console_TOP__DOT__cache_emem_addr;
        IData/*31:0*/ Game_Console_TOP__DOT__cache_emem_wdata;
        IData/*31:0*/ Game_Console_TOP__DOT__dec_emem_rdata;
        IData/*31:0*/ Game_Console_TOP__DOT__dec_ddr3_rdata;
        IData/*31:0*/ Game_Console_TOP__DOT__ppu_emem_addr;
        IData/*31:0*/ Game_Console_TOP__DOT__ppu_emem_wdata;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_insn;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__eoi;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__reg_pc;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__reg_next_pc;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__reg_op1;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__reg_op2;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__reg_out;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__next_insn_opcode;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_insn_opcode;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_insn_addr;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__next_pc;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__irq_mask;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__irq_pending;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__timer;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__i;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_mul_rd;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_div_rd;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__pcpi_int_rd;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_rdata_word;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_rdata_q;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__mem_rdata_latched_noshuffle;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoded_imm;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__decoded_imm_j;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_insn_imm;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_rs1val;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_rs2val;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__q_insn_imm;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__q_insn_opcode;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cached_insn_imm;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cached_insn_opcode;
        WData/*127:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_ascii_state[4];
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__current_pc;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__next_irq_pending;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_out;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__alu_out_q;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cpuregs_wrdata;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cpuregs_rs1;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cpuregs_rs2;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__dividend;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__quotient;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__quotient_msk;
        IData/*31:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__i;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__proc_final_pixel_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__font_mixed_pixel_RGB;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_next_ad;
        IData/*31:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__tem_32_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache1_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache2_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache3_RGB;
    };
    struct {
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__cache4_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req1_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req2_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req3_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req4_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req5_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req6_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req7_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req8_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req9_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req10_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req11_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_rgb__DOT__req12_exclusive_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z1_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z2_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z3_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z4_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z5_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z6_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z7_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z8_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z9_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__Z10_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_1_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_2_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_3_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_4_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_5_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_6_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_7_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_8_reg;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_1;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_2;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_3;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_4;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_5;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_6;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_7;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_8;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__organized_RGB;
        QData/*35:0*/ Game_Console_TOP__DOT__u_cpu__DOT__trace_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__count_cycle;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__count_instr;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__new_ascii_instr;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__dbg_ascii_instr;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__q_ascii_instr;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cached_ascii_instr;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__rs1;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__rs2;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__rd;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__rdx;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs1;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__next_rs2;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__this_rs2;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__next_rd;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdx;
        QData/*63:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT__next_rdt;
        QData/*62:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__divisor;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__bg1_comp_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__bg2_comp_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__ch1_comp_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__ch2_comp_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__ch3_comp_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__ch4_comp_data;
    };
    struct {
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__uni1_comp_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__uni2_comp_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__sc_comp_data;
        QData/*63:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__st_comp_data;
        CData/*7:0*/ Game_Console_TOP__DOT__line_visible[15];
        SData/*8:0*/ Game_Console_TOP__DOT__line_rgb[15];
        CData/*2:0*/ Game_Console_TOP__DOT__line_alpha[15];
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT__cpuregs[36];
        IData/*31:0*/ Game_Console_TOP__DOT__u_icache__DOT__word_buffer[4];
        IData/*31:0*/ Game_Console_TOP__DOT__u_icache__DOT__word_buffer_wdata[4];
        IData/*31:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT__ppu_regs[43];
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__Req_RGB[12];
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__Req_trans[12];
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__Req_end[12];
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__layer_RGB[11];
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__layer_is_trans[11];
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__layer_valid[11];
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__layer_z[11];
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__layer_a[11];
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__layer_ready[11];
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__z_index_map[10];
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__z_input_RGB[10];
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__z_input_is_trans[10];
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__z_input_a[10];
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__z_input_valid[10];
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__z_input_ready[10];
    };
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap1;
        CData/*3:0*/ Game_Console_TOP__DOT__u_cpu__DOT__genblk2__DOT__pcpi_mul__DOT____Vconcswap2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req12_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req11_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req10_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req10_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req9_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req9_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req8_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req8_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req7_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req7_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req6_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req6_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req5_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req5_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req4_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req4_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req3_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req3_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req2_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req2_trans;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req1_end;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req1_trans;
        CData/*3:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound2;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound4;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound5;
        CData/*7:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound6;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound7;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound8;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound9;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound10;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound11;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound12;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound13;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound14;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound15;
        CData/*0:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound16;
        CData/*7:0*/ __Vtableidx1;
        CData/*4:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__reg_sh;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__decoder_trigger;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__decoder_pseudo_trigger;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__do_waitirq;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__mem_do_rinst;
        CData/*1:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__mem_wordsize;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__latched_is_lu;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__latched_is_lh;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__latched_is_lb;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__irq_active;
        CData/*5:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__latched_rd;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__latched_compr;
        CData/*1:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__irq_state;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__mem_do_prefetch;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__cpu_state;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__pcpi_valid;
        CData/*3:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__pcpi_timeout_counter;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__instr_div;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__instr_divu;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__instr_rem;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__genblk4__DOT__pcpi_div__DOT__instr_remu;
        CData/*0:0*/ __Vdlyvset__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v0;
        CData/*0:0*/ __Vdlyvset__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v1;
        CData/*0:0*/ __Vdlyvset__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v2;
        CData/*0:0*/ __Vdlyvset__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v3;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v4;
        CData/*5:0*/ __Vdlyvdim0__Game_Console_TOP__DOT__u_addr_decoder__DOT__ppu_regs__v0;
        CData/*0:0*/ __Vdlyvset__Game_Console_TOP__DOT__u_addr_decoder__DOT__ppu_regs__v0;
        CData/*0:0*/ __Vdlyvset__Game_Console_TOP__DOT__u_addr_decoder__DOT__ppu_regs__v1;
        CData/*0:0*/ __Vdlyvset__Game_Console_TOP__DOT__u_addr_decoder__DOT__ppu_regs__v2;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_fifo_count;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_fifo_count;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_fifo_count;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_fifo_count;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_fifo_count;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_fifo_count;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_fifo_count;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_fifo_count;
        CData/*3:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__main_state;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_fifo_rear;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_fifo_rear;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_fifo_rear;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_fifo_rear;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_fifo_rear;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_fifo_rear;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_fifo_rear;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_fifo_rear;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__emem_r_counter;
        CData/*3:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__output_state;
        CData/*3:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__pixel_state;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_1_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_2_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_3_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_4_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_5_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_6_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_7_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_1_reg_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_2_reg_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_3_reg_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_4_reg_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_5_reg_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_6_reg_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_7_reg_valid;
        CData/*3:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__font_state;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__fontmap_skid_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__korea_bitmap_skid_valid;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__ascii_bitmap_skid_valid;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__ascii_bitmap_skid_data;
        CData/*0:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__custom_tile_bitmap_skid_valid;
        CData/*7:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__custom_tile_bitmap_skid_data;
        CData/*5:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_0_39;
        CData/*3:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_0_15;
        CData/*5:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__counter_font_x;
        CData/*0:0*/ __Vclklast__TOP__clk;
        CData/*0:0*/ __Vclklast__TOP__resetn;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_bg1__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_bg2__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_ch1__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_ch2__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_ch3__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_ch4__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_sc__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_st__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_un1__rgb_convert_end;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_un2__rgb_convert_end;
        SData/*8:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_fifo_count;
        SData/*8:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_fifo_count;
        SData/*8:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_fifo_rear;
    };
    struct {
        SData/*8:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_fifo_rear;
        SData/*9:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__should_read_layer;
        SData/*8:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__output_pixel_x;
        SData/*15:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__fontmap_skid_data;
        SData/*15:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__korea_bitmap_skid_data;
        IData/*31:0*/ Game_Console_TOP__DOT__u_cpu__DOT____Vlvbound1;
        IData/*31:0*/ Game_Console_TOP__DOT__u_addr_decoder__DOT____Vlvbound1;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req12_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req11_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req10_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req9_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req8_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req7_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req6_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req5_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req4_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req3_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req2_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT____Vcellout__u_rgb__Req1_RGB;
        IData/*17:0*/ Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT____Vlvbound3;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__reg_out;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__timer;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__reg_pc;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__reg_op1;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__irq_mask;
        IData/*31:0*/ __Vdlyvval__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v0;
        IData/*31:0*/ __Vdlyvval__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v1;
        IData/*31:0*/ __Vdlyvval__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v2;
        IData/*31:0*/ __Vdlyvval__Game_Console_TOP__DOT__u_icache__DOT__word_buffer__v3;
        IData/*31:0*/ __Vdlyvval__Game_Console_TOP__DOT__u_addr_decoder__DOT__ppu_regs__v0;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni1_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__uni2_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__status_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__script_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char1_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char2_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char3_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__char4_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back1_next_ad;
        IData/*31:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_pixel_fifo__DOT__u_compressed_fifo__DOT__back2_next_ad;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_1;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_2;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_3;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_4;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_5;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_6;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__mixed_RGB_7;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_1_reg;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_2_reg;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_3_reg;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_4_reg;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_5_reg;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_6_reg;
        IData/*17:0*/ __Vdly__Game_Console_TOP__DOT__u_ppu__DOT__u_font__DOT__RGB_7_reg;
        QData/*63:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__count_cycle;
        QData/*63:0*/ __Vdly__Game_Console_TOP__DOT__u_cpu__DOT__count_instr;
        CData/*0:0*/ __Vchglast__TOP__Game_Console_TOP__DOT__u_ppu__DOT__u_proc__DOT__layer_ready[11];
        CData/*0:0*/ __Vm_traceActivity[5];
    };
    static WData/*127:0*/ __Vtable1_Game_Console_TOP__DOT__u_cpu__DOT__dbg_ascii_state[256][4];
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    VGame_Console_TOP__Syms* __VlSymsp;  // Symbol table
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(VGame_Console_TOP);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible with respect to DPI scope names.
    VGame_Console_TOP(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~VGame_Console_TOP();
    /// Trace signals in the model; called by application code
    void trace(VerilatedVcdC* tfp, int levels, int options = 0);
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(VGame_Console_TOP__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(VGame_Console_TOP__Syms* symsp, bool first);
  private:
    static QData _change_request(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static QData _change_request_1(VGame_Console_TOP__Syms* __restrict vlSymsp);
  public:
    static void _combo__TOP__10(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static void _combo__TOP__9(VGame_Console_TOP__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _eval(VGame_Console_TOP__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(VGame_Console_TOP__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(VGame_Console_TOP__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _sequent__TOP__11(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static void _sequent__TOP__3(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static void _sequent__TOP__4(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static void _sequent__TOP__5(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static void _sequent__TOP__6(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static void _sequent__TOP__7(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static void _sequent__TOP__8(VGame_Console_TOP__Syms* __restrict vlSymsp);
    static void _settle__TOP__1(VGame_Console_TOP__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__2(VGame_Console_TOP__Syms* __restrict vlSymsp) VL_ATTR_COLD;
  private:
    static void traceChgSub0(void* userp, VerilatedVcd* tracep);
    static void traceChgTop0(void* userp, VerilatedVcd* tracep);
    static void traceCleanup(void* userp, VerilatedVcd* /*unused*/);
    static void traceFullSub0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceFullTop0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInitSub0(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInitTop(void* userp, VerilatedVcd* tracep) VL_ATTR_COLD;
    void traceRegister(VerilatedVcd* tracep) VL_ATTR_COLD;
    static void traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
